spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: lab_286338407
    password: 75062e1cf53c_#@Aa
    url: jdbc:mysql://rm-bp17rs6x3634h47kkdo.mysql.rds.aliyuncs.com:3306/jssdMySql
#    type: com.zaxxer.hikari.util.DriverDataSource